name: Create PDFs and publish to GitHub pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Prepare Build
      uses: srt32/git-actions@v0.0.3
      with:
        args: ./build.sh prepare
    - name: Build
      uses: docker://fbenz/pdflatex
      if: github.event.deleted == false
      with:
        args: ./build.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
    - name: Prepare Unredacted Build
      run: |
        echo -e "\\renewcommand\\myaddressone{$ADDRESS1}\n\\newcommand\\myaddresstwo{$ADDRESS2}\\newcommand\\myphone{$PHONE_NO}" >myinfo.tex
        cat myinfo.tex
      env:
        ADDRESS1: ${{ secrets.MY_ADDRESS1 }}
        ADDRESS2: ${{ secrets.MY_ADDRESS2 }}
        PHONE_NO: ${{ secrets.MY_PHONE_NO }}
    - name: Build Unredacted
      uses: docker://fbenz/pdflatex
      if: github.event.deleted == false
      with:
        args: ./build.sh -p unredacted
    - name: Store
      uses: actions/aws/cli@master
      with:
        args: s3 sync unredacted/*.pdf s3://resume-unredacted.369.dk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
